// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADaZLCOLHraKDbWjwKIqsJRmaoEJWsotQ',
    appId: '1:574909873629:web:cc52ea5fd78ed5553bca34',
    messagingSenderId: '574909873629',
    projectId: 'i-canyon-marketing-app',
    authDomain: 'i-canyon-marketing-app.firebaseapp.com',
    storageBucket: 'i-canyon-marketing-app.firebasestorage.app',
    measurementId: 'G-9V1GJ62HEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm46HN25WiQC5f1W03wAkJzLi_3us76Iw',
    appId: '1:574909873629:android:a238441b1187f24d3bca34',
    messagingSenderId: '574909873629',
    projectId: 'i-canyon-marketing-app',
    storageBucket: 'i-canyon-marketing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRtaD2D4tLk-JvZpDIS0B7gA5_jawh_9s',
    appId: '1:574909873629:ios:ac1664f88a9cb62e3bca34',
    messagingSenderId: '574909873629',
    projectId: 'i-canyon-marketing-app',
    storageBucket: 'i-canyon-marketing-app.firebasestorage.app',
    iosBundleId: 'com.icanyontechnologies.refrrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRtaD2D4tLk-JvZpDIS0B7gA5_jawh_9s',
    appId: '1:574909873629:ios:6fc861db1e1d76ac3bca34',
    messagingSenderId: '574909873629',
    projectId: 'i-canyon-marketing-app',
    storageBucket: 'i-canyon-marketing-app.firebasestorage.app',
    iosBundleId: 'com.icanyon.firstmarketingapp',
  );
}